name: Create Release

on:
  workflow_call:
    secrets:
      token:
        required: true
    inputs:
      pre_release:
        type: boolean
        description: 'Pre-release'
        required: false
        default: false
      generate_release_notes:
        type: boolean
        description: 'Generate release notes'
        required: false
        default: true
      is_draft:
        type: boolean
        description: 'Is draft'
        required: false
        default: false

jobs:
  CreateRelease:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.token }}
        with:
          generateReleaseNotes: ${{ inputs.generate_release_notes }}
          draft: ${{ inputs.is_draft }}
          prerelease: ${{ inputs.pre_release }}

  WriteVersionFile:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - id: previousTag
        uses: 'WyriHaximus/github-action-get-previous-tag@master'

      - name: WriteVersionFile
        id: writeVersionFile
        run: |
          rm -f ./.version
          echo ${{ steps.previousTag.outputs.tag }} >> .version

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: main
          commit_message: WriteVersionFile
          commit_user_name: EncoreBot
          commit_user_email: ghbot@encoredigitalgroup.com