name: Create Release

on:
  workflow_call:
    secrets:
      token:
        required: true
    inputs:
      pre_release:
        type: boolean
        description: 'Pre-release'
        required: false
        default: false
      generate_release_notes:
        type: boolean
        description: 'Generate release notes'
        required: false
        default: true
      is_draft:
        type: boolean
        description: 'Is draft'
        required: false
        default: false

jobs:
  CreateRelease:
    name: CreateRelease
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.token }}
        with:
          generateReleaseNotes: ${{ inputs.generate_release_notes }}
          draft: ${{ inputs.is_draft }}
          prerelease: ${{ inputs.pre_release }}
