name: Monorepo Split

on:
  workflow_call:
    secrets:
      token:
        required: true
    
    inputs:
      targetBranch:
        type: string
        description: 'Branch to target workflow against'
        required: false
        default: 'main'
      
      package:
        type: string
        description: 'Package to be split'
        required: true
      
      orgName:
        type: string
        description: 'Name of the GitHub organization'
        required: true
      
      commitUsername:
        type: string
        description: 'Name of the committer'
        required: false
        default: 'Marc Beinder'
      
      commitEmailAddress:
        type: string
        description: 'Email address of the committer'
        required: false
        default: 'marc.beinder@encoredigitalgroup.com'

jobs:
  SplitMonorepo:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Code'
        id: actionCheckout
        uses: actions/checkout@v3

      - name: 'Get Previous Tag'
        id: previousTag
        uses: 'WyriHaximus/github-action-get-previous-tag@master'

      - name: 'Monorepo Split of ${{ matrix.package }}'
        id: splitStep
        uses: danharrin/monorepo-split-github-action@v2.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          package_directory: 'src/${{ inputs.package }}'
          repository_organization: ${{ inputs.orgName }}
          repository_name: ${{ inputs.package }}
          branch: ${{ inputs.targetBranch }}
          tag: ${{ steps.previousTag.outputs.tag }}
          user_name: ${{ inputs.commitUsername }}
          user_email: ${{ inputs.commitEmailAddress }}
